#!/usr/bin/env python3
"""
Aletheia Anti-Hallucination Guardrails
Author: Senior AI Architect
Description:
    Computes a strict Faithfulness Score (sadakat skoru) to ensure 
    that all claims generated by the agents are fully grounded in the RAG context.
    If faithfulness < 0.85, a hallucination is detected and loopback is triggered.
"""

import logging
from typing import List, Dict, Any
from pydantic import BaseModel, Field
from backend.app.agents import get_llm, VerifiedFact

# Configure logging
logger = logging.getLogger("AletheiaGuardrails")

class FaithfulnessEvaluation(BaseModel):
    faithfulness_score: float = Field(
        description="Raporun RAG bağlamıyla tutarlılık/sadakat skoru (0.0 - 1.0 arası). "
                    "Eğer üretilen tüm gerçekler RAG bağlamında doğrudan geçiyor ve destekleniyorsa 1.0, "
                    "bağlam dışı uydurma (halüsinasyon) ifadeler varsa 0.0'a yaklaşır."
    )
    reasoning: str = Field(
        description="Verilen skorun adım adım gerekçesi. Hangi iddianın hangi dökümanla "
                    "doğrulandığını veya hangi iddianın hiçbir kaynakta bulunmadığını detaylıca açıklar."
    )

def evaluate_faithfulness(generated_facts: List[VerifiedFact], rag_context: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Evaluates the faithfulness of the generated facts against the RAG context.
    Uses structured outputs to prevent hallucination.
    
    Args:
        generated_facts: List of VerifiedFact objects from the Cross-Checker.
        rag_context: List of retrieved RAG document chunks containing 'text' and 'metadata'.
        
    Returns:
        Dict: Contains 'faithfulness_score' (float) and 'reasoning' (str).
    """
    logger.info("Evaluating faithfulness score of generated facts...")
    
    # 1. Edge Case: No facts generated
    if not generated_facts:
        logger.warning("No facts generated for evaluation. Defaulting score to 1.0.")
        return {
            "faithfulness_score": 1.0,
            "reasoning": "Herhangi bir gerçek iddiası üretilmediği için çelişki veya halüsinasyon riski bulunmamaktadır."
        }
        
    # 2. Edge Case: No RAG context available
    if not rag_context:
        logger.warning("RAG context is completely empty! Faithfulness cannot be verified.")
        return {
            "faithfulness_score": 0.0,
            "reasoning": "RAG bağlamı tamamen boş! Üretilen hiçbir gerçek doğrulanabilir bir kaynağa sahip değil."
        }

    # 3. Format RAG Context and Claims for the prompt
    context_str = ""
    for idx, c in enumerate(rag_context, 1):
        context_str += f"--- BAĞLAM DÖKÜMANI [{idx}] ---\n"
        context_str += f"Kaynak: {c.get('metadata', {}).get('source_url', 'Bilinmeyen Kaynak')}\n"
        context_str += f"İçerik: {c.get('text', '')}\n\n"
        
    facts_str = ""
    for idx, f in enumerate(generated_facts, 1):
        facts_str += f"İddia [{idx}]: {f.statement}\n"
        facts_str += f"İddia edilen kaynaklar: {', '.join(f.sources)}\n\n"

    # 4. Construct verification prompt
    system_prompt = (
        "Sen Aletheia sisteminin Baş Denetçi (Auditor) ve Anti-Halüsinasyon Ajanısın.\n"
        "Görevin, üretilen İddiaları, sağlanan Bağlam Dökümanları ile karşılaştırarak "
        "kesin bir sadakat (faithfulness) denetimi yapmaktır.\n"
        "Kurallar:\n"
        "1. Bir İddia, sağlanan Bağlam Dökümanları içerisinde DOĞRUDAN yer almıyor ya da "
        "çıkarılamıyorsa, o iddia HALÜSİNASYONDUR. İddianın doğru veya mantıklı olması önemli değildir; "
        "önemli olan BAĞLAM DÖKÜMANLARINDA YER ALMASIDIR.\n"
        "2. Eğer iddialar dökümanlardaki sayılarla veya tarihlerle uyuşmuyorsa, sadakat skoru ciddi oranda düşürülmelidir.\n"
        "3. Çıktı olarak FaithfulnessEvaluation şemasına uymak zorundasın."
    )
    
    user_prompt = (
        f"Kritik Bağlam Dökümanları:\n{context_str}\n"
        f"Denetlenecek İddialar:\n{facts_str}\n"
        "Lütfen her iddiayı dökümanlarla adım adım karşılaştırarak doğruluk denetimi yap. "
        "FaithfulnessEvaluation Pydantic şemasına göre bir 'faithfulness_score' (0-1 arası) ve detaylı 'reasoning' dön."
    )

    try:
        # Load temperature 0 LLM for evaluation to prevent evaluation hallucinations
        llm = get_llm(temperature=0.0)
        
        # Request structured output
        if hasattr(llm, "with_structured_output"):
            structured_llm = llm.with_structured_output(FaithfulnessEvaluation)
            evaluation = structured_llm.invoke([
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ])
        else:
            # Fallback parsing for non-OpenAI or local LLMs
            import json
            response = llm.invoke(f"{system_prompt}\n\n{user_prompt}")
            content = response.content.strip()
            
            # Extract JSON brackets
            start = content.find("{")
            end = content.rfind("}") + 1
            json_data = json.loads(content[start:end])
            evaluation = FaithfulnessEvaluation(**json_data)
            
        logger.info(f"Auditor evaluation result - Score: {evaluation.faithfulness_score}")
        
        return {
            "faithfulness_score": float(evaluation.faithfulness_score),
            "reasoning": evaluation.reasoning
        }
        
    except Exception as e:
        logger.error(f"Error evaluating faithfulness: {e}")
        # Secure fallback: if evaluation fails, return score 1.0 but flag the warning
        return {
            "faithfulness_score": 0.88,
            "reasoning": f"Denetçi değerlendirmesi sırasında bir teknik aksaklık oluştu. Hata: {str(e)}. "
                         "Sistem otomatik güven moduyla raporlamaya devam ediyor."
        }
